// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvhpE3qfPqdOI0wxh1_WCv8dsFRUOfNg',
    appId: '1:240055649561:web:bcb38ca49a97dc611ab188',
    messagingSenderId: '240055649561',
    projectId: 'safesnake-app',
    authDomain: 'safesnake-app.firebaseapp.com',
    storageBucket: 'safesnake-app.appspot.com',
    measurementId: 'G-R00ZBV51R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKy5vW5V93CPyPTEEJQqlrGqhIx3z9JQw',
    appId: '1:240055649561:android:8d748023149bb4b61ab188',
    messagingSenderId: '240055649561',
    projectId: 'safesnake-app',
    storageBucket: 'safesnake-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsdZ4q_F2gKm8hr1GG2lkM6A3SXlGOZ0',
    appId: '1:240055649561:ios:c3dcaec5820eea8d1ab188',
    messagingSenderId: '240055649561',
    projectId: 'safesnake-app',
    storageBucket: 'safesnake-app.appspot.com',
    iosBundleId: 'io.github.danfq.safesnake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsdZ4q_F2gKm8hr1GG2lkM6A3SXlGOZ0',
    appId: '1:240055649561:ios:ac6ea852f2f4e9d81ab188',
    messagingSenderId: '240055649561',
    projectId: 'safesnake-app',
    storageBucket: 'safesnake-app.appspot.com',
    iosBundleId: 'io.github.danfq.safesnake.RunnerTests',
  );
}
